import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/About";
import Copyrights from "../components/Copyrights";
import Works from "../components/Works";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="sr-only">Portfolio</h1>
        <About />
        <Works />
      </main>

      <footer>
        <Copyrights />
      </footer>
    </div>
  );
};

export default Home;
